env:
  global:
    - TERM=dumb
notifications:
  email: false
git:
  quiet: true
  depth: false
language: java
jdk: openjdk8
python: 3.7
os: linux
arch: amd64
install: true
services: docker
addons:
  apt:
    update: true
    packages:
      - curl
      - python3-pip
      - libhsdis0-fcml
      - docker-ce
before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user --upgrade pip setuptools
  - pip  install --user --upgrade docker-compose httpie
  - docker-compose version
  - |
    if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ${HOME}/.local/daggerok/bash-functions/master
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash
    fi
    source ~/.local/daggerok/bash-functions/master/main.bash
  - stop_any 80 1234 8080 5432
  - ulimit -c unlimited
jobs:
  include:
    - stage: test
      name: persist-all
      script:
        - cd $TRAVIS_BUILD_DIR/persist-all && ./sbtw clean h2FileInit "runMain com.github.daggerok.akka.Main"
        - cd $TRAVIS_BUILD_DIR/persist-all && ./sbtw h2FileNext "runMain com.github.daggerok.akka.Main"
    - stage: test
      name: akka-persistence-h2-starter h2FileNext
      script:
        - cd $TRAVIS_BUILD_DIR/akka-persistence-h2-starter && ./sbtw clean h2FileInit "runMain com.github.daggerok.akka.Main"
        - cd $TRAVIS_BUILD_DIR/akka-persistence-h2-starter && ./sbtw h2FileNext "runMain com.github.daggerok.akka.Main"
    - stage: test
      name: akka-persistence-h2-starter h2FileInit
      script: cd $TRAVIS_BUILD_DIR/akka-persistence-h2-starter && ./sbtw clean h2FileInit "runMain com.github.daggerok.akka.Main"
    - stage: test
      name: akka-persistence-h2-starter h2Mem
      script: cd $TRAVIS_BUILD_DIR/akka-persistence-h2-starter && ./sbtw clean h2Mem "runMain com.github.daggerok.akka.Main"
    - stage: test
      name: akka-persistence-h2-starter stateful file
      script:
        - cd $TRAVIS_BUILD_DIR/akka-persistence-h2-starter
        - cp -Rf ./src/main/resources/application-file-init.conf ./src/main/resources/application.conf
        - ./sbtw clean "runMain com.github.daggerok.akka.Main"
        - cp -Rf ./src/main/resources/application-file-next.conf ./src/main/resources/application.conf
        - ./sbtw "runMain com.github.daggerok.akka.Main"
    - stage: test
      name: akka-persistence-h2-starter stateless file
      script:
        - cp -Rf $TRAVIS_BUILD_DIR/akka-persistence-h2-starter/src/main/resources/application-file-init.conf $TRAVIS_BUILD_DIR/akka-persistence-h2-starter/src/main/resources/application.conf
        - cd $TRAVIS_BUILD_DIR/akka-persistence-h2-starter && ./sbtw "runMain com.github.daggerok.akka.Main"
    - stage: test
      name: akka-persistence-h2-starter stateless mem
      script:
        - cp -Rf $TRAVIS_BUILD_DIR/akka-persistence-h2-starter/src/main/resources/application-mem.conf $TRAVIS_BUILD_DIR/akka-persistence-h2-starter/src/main/resources/application.conf
        - cd $TRAVIS_BUILD_DIR/akka-persistence-h2-starter && ./sbtw "runMain com.github.daggerok.akka.Main"
    - stage: test
      name: akka-persistence-starter
      script: cd $TRAVIS_BUILD_DIR/akka-persistence-starter && ./sbtw "runMain com.github.daggerok.akka.Main"
    - stage: test
      name: akka-persistence-postgres-starter
      script:
        - cd $TRAVIS_BUILD_DIR/akka-persistence-postgres-starter && ./sbtw "dockerComposeRestart skipPull" "runMain com.github.daggerok.akka.Main"
        - cd $TRAVIS_BUILD_DIR/akka-persistence-postgres-starter && ./sbtw "runMain com.github.daggerok.akka.Main" dockerComposeStop
    - stage: test
      name: akka-typed-starter AkkaActorTyped
      script: cd $TRAVIS_BUILD_DIR/akka-typed-starter && ./sbtw clean "runMain com.github.daggerok.akka.AkkaActorTyped"
    - stage: test
      name: akka-typed-starter AskPattern
      script: cd $TRAVIS_BUILD_DIR/akka-typed-starter && ./sbtw clean package "runMain com.github.daggerok.akka.AskPattern"
    - stage: test
      name: akka-typed-starter build
      script: cd $TRAVIS_BUILD_DIR/akka-typed-starter && ./sbtw clean package
cache:
  pip: true
  packages: true
  directories:
    - $HOME/.m2
    - $HOME/.sbt
    - $HOME/.ivy
    - $HOME/.gradle
    - $HOME/.docker
    - $HOME/.local/daggerok
