env:
  global:
    - TERM=dumb
notifications:
  email: false
git:
  quiet: true
  depth: false
language: java
jdk: openjdk8
python: 3.7
os: linux
arch: amd64
install: true
services: docker
addons:
  apt:
    update: true
    packages:
      - curl
      - python3-pip
      - libhsdis0-fcml
      - docker-ce
before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user --upgrade pip setuptools
  - pip  install --user --upgrade docker-compose httpie
  - docker-compose version
  - |
    if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ${HOME}/.local/daggerok/bash-functions/master
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash
    fi
    source ~/.local/daggerok/bash-functions/master/main.bash
  - stop_any 80 1234 8080 5432
  - ulimit -c unlimited
jobs:
  include:
    - stage: test
      name: akka-persistence-starter
      script:
        - cd $TRAVIS_BUILD_DIR/akka-persistence-starter && ./sbtw "dockerComposeRestart skipPull" "runMain com.github.daggerok.akka.Main"
        - cd $TRAVIS_BUILD_DIR/akka-persistence-starter && ./sbtw "runMain com.github.daggerok.akka.Main" dockerComposeStop
    - stage: test
      name: akka-typed-starter AkkaActorTyped
      script: cd $TRAVIS_BUILD_DIR/akka-typed-starter && ./sbtw clean "runMain com.github.daggerok.akka.AkkaActorTyped"
    - stage: test
      name: akka-typed-starter AskPattern
      script: cd $TRAVIS_BUILD_DIR/akka-typed-starter && ./sbtw clean package "runMain com.github.daggerok.akka.AskPattern"
    - stage: test
      name: akka-typed-starter build
      script: cd $TRAVIS_BUILD_DIR/akka-typed-starter && ./sbtw clean package
cache:
  pip: true
  packages: true
  directories:
    - $HOME/.m2
    - $HOME/.sbt
    - $HOME/.ivy
    - $HOME/.gradle
    - $HOME/.docker
    - $HOME/.local/daggerok
