version: '2.1'
services:
  postgres:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_DB: akka
      POSTGRES_USER: akka
      POSTGRES_PASSWORD: akka
    ports: ['5432:5432']
    healthcheck:
      test: pg_isready --host=127.0.0.1 --port=5432 --dbname=$$POSTGRES_DB --username=$$POSTGRES_USER
      #test: ['CMD', 'pg_isready', '-h', '127.0.0.1', '-p', '5432', '-d', '$$POSTGRES_DB', '-U', '$$POSTGRES_USER']
      timeout: 1s
      retries: 99
      interval: 3s
    volumes: ['./postgres/docker-entrypoint-initdb.d/V__001_ddl.sql:/docker-entrypoint-initdb.d/V__001_ddl.sql']
